version: '3'  
services:  
  app:  
    image: coolify/coolify:latest  
    ports:  
      - "8000:8000"  
    environment:  
      - COOLIFY_ENV=production  
      - DB_HOST=db  
      - DB_PORT=5432  
      - DB_USER=coolify  
      - DB_PASSWORD=${COOLIFY_DB_PASSWORD}  
      - SECRET_KEY=${COOLIFY_SECRET}  
    depends_on:  
      - db  
  db:  
    image: postgres:14  
    environment:  
      - POSTGRES_USER=coolify  
      - POSTGRES_PASSWORD=${COOLIFY_DB_PASSWORD}  
      - POSTGRES_DB=coolify  